-- MySQL Script generated by MySQL Workbench
-- Tue Apr 28 11:24:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema corridas_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema corridas_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `corridas_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `corridas_db` ;

-- -----------------------------------------------------
-- Table `corridas_db`.`corredores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corridas_db`.`corredores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `turma` VARCHAR(255) NOT NULL,
  `equipe` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `corridas_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corridas_db`.`users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_users`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `corridas_db`.`voltas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `corridas_db`.`voltas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tempo` DECIMAL(10,0) NOT NULL,
  `data` TIMESTAMP NOT NULL,
  `corredores_id` INT NOT NULL,
  `numero_volta` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_voltas_corredores_idx` (`corredores_id` ASC) VISIBLE,
  CONSTRAINT `fk_voltas_corredores`
    FOREIGN KEY (`corredores_id`)
    REFERENCES `corridas_db`.`corredores` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
